FROM python:3.9-slim

WORKDIR /app

# Copy requirements file and install dependencies
COPY requirements.txt .
RUN pip install -U pip && \
    pip install -r requirements.txt

# Copy application code
COPY src/ ./src/

# Expose the port Gradio will run on
EXPOSE 7860

# Set environment variables
ENV PYTHONUNBUFFERED=1

# Run the Gradio app
CMD ["python", "src/ui/esg_gradio.py"]
